// frontend/src/views/Demo.vue
<script setup>
import { NResult, NCard, NButton } from 'naive-ui'
import { onMounted, ref } from "vue";
import { useMessage } from 'naive-ui'
import { useRoute, useRouter } from 'vue-router'

import { api } from '../api';
import { useGlobalState } from '../store'

const { jwtSession, appIdSession } = useGlobalState()
const message = useMessage();
const route = useRoute();
const router = useRouter();

const user = ref(null);

const signOut = () => {
    jwtSession.value = null;
    user.value = null;
    router.push('/demo');
}

onMounted(async () => {
    const code = route.query.code;
    if (!code && !jwtSession.value) {
        return;
    }
    if (code) {
        try {
            const { jwt } = await api.fetch("/api/token", {
                method: "POST",
                message: message,
                body: JSON.stringify({
                    app_id: appIdSession.value || "demo",
                    app_secret: "demo_secret",
                    code: code,
                })
            });
            jwtSession.value = jwt;
        } catch (error) {
            message.error(error.message || "登录失败");
            return;
        }
        router.push('/demo');
    }
    try {
        const app_id = appIdSession.value || "demo";
        user.value = await api.fetch(`/api/info?app_id=${app_id}`, {
            message: message,
            headers: {
                'Authorization': `Bearer ${jwtSession.value}`,
                'Content-Type': 'application/json',
            }
        });
    } catch (error) {
        message.error(error.message || "获取用户信息失败");
    }
})
</script>

<template>
    <div class="main">
        <n-card>
            <h2>用户信息</h2>
            <pre v-if="user">{{ JSON.stringify(user, null, 2) }}</pre>
            <p v-else>
                您还没有登录
            </p>
            <n-button @click="router.push('login')" type="primary" block secondary strong>
                返回登录
            </n-button>
            <n-button @click="signOut" v-if="user" type="primary" block secondary strong>
                退出登录
            </n-button>
        </n-card>
    </div>
</template>

<style scoped>
.main {
    display: flex;
    text-align: left;
    place-items: center;
    justify-content: center;
}

.n-card {
    max-width: 600px;
    margin: 20px;
}
</style>

// frontend/src/components/demo.tsx
import { cn } from "@/lib/utils";
import { Link, useSearchParams } from "react-router";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { useGlobal } from "@/components/global-provider";
import { toast } from "sonner";
import { UseApiClient } from "@/api";

export function Demo({
    className,
    ...props
}: React.ComponentPropsWithoutRef<"div">) {
    const { apiFetch } = UseApiClient()
    const [URLSearchParams] = useSearchParams();
    const { jwtSession, setJwtSession, appIdSession } = useGlobal();
    const [user, setUser] = useState<Record<string, string>>({});
    useEffect(() => {
        const code = URLSearchParams.get("code");
        const loginApiCall = async () => {
            if (!code && !jwtSession) {
                return;
            }
            if (code) {
                try {
                    const { jwt } = await apiFetch<{
                        jwt: string;
                    }>("/api/token", {
                        method: "POST",
                        body: JSON.stringify({
                            app_id: appIdSession || "demo",
                            app_secret: "demo_secret",
                            code: code,
                        })
                    });
                    setJwtSession(jwt);
                } catch (error) {
                    toast.error((error as Error).message || "登录失败");
                    return;
                }
                window.location.href = "/demo";
                return;
            }
            try {
                const app_id = appIdSession || "demo";
                const user_res = await apiFetch<
                    Record<string, string>
                >(`/api/info?app_id=${app_id}`, {
                    headers: {
                        'Authorization': `Bearer ${jwtSession}`,
                        'Content-Type': 'application/json',
                    }
                });
                setUser(user_res);
            } catch (error) {
                toast.error((error as Error).message || "获取用户信息失败");
            }
        }
        loginApiCall();
    }, []);

    return (
        <div className={cn("flex flex-col gap-6", className)} {...props}>
            <Card>
                <CardHeader className="text-center">
                    <CardTitle className="text-xl">用户信息</CardTitle>
                </CardHeader>
                <CardContent>
                    {(user && Object.keys(user).length > 0) ?
                        (
                            <pre className="text-sm whitespace-pre-wrap break-all">{JSON.stringify(user, null, 2)}</pre>
                        ) : (
                            <p className="text-sm">您还没有登录</p>
                        )}
                    <Button variant="outline" asChild className="w-full">
                        <Link to="/">返回登录</Link>
                    </Button>
                </CardContent>
            </Card>
        </div>
    )
}
